FROM docker.io/bitnami/spark:3.5.3

USER root

# Install python3-pip
# RUN apt-get update && apt-get install -y python3-pip

# Install TensorFlow
# RUN pip3 install tensorflow

# Install tensorflow-cpu for a smaller footprint
RUN pip3 install --no-cache-dir tensorflow-cpu

# Add any additional required packages
RUN pip3 install --no-cache-dir \
    numpy \
    pandas \
    scikit-learn

USER 1001